### PR TITLE
allow import 'react/addons' as well as 'react'

### PR DESCRIPTION
**Pull request by alunny**
Quick fix for #3

### CODE REVIEW

**Comment by rxaviers** [comment]
Awesome, thanks. Could you sign-off your commit please?

**Comment by alunny** [comment]
Will do. Is there any way to automate that, btw?

**Comment by rxaviers** [comment]
We also should add a testcase for such fix

**Comment by rxaviers** [comment]
`git commit --amend -s` should do it

**Comment by alunny** [comment]
Will do (for the testcase)

**Comment by rxaviers** [comment]
Thanks and sorry for the sign-off bothering.

**Comment by rxaviers** [comment]
Thank you @alunny. Released as `0.0.5`.

**Pull request closed without merging**
